# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Master Build CI

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-webapp:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.804'

    - name: Build with dotnet
      run: dotnet build --configuration Release

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
     
     #Publish webapp artifacts
    - name: Upload WebApp Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApp
        path: ${{env.DOTNET_ROOT}}/myapp
    
     #Publish webapp artifacts
    - name: Upload WebApp Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: WebApp
        path: ${{GITHUB_WORKSPACE}}/ARMTemplates
